### ISSUE TITLE
error: pathspec on windows git bash

### ISSUE THREAD

**Issue by vaspoz** [RomanHotsiy/commitgpt#9]
I'm using that tool on Win git bash.
Got this error:
√ Pick a message · Update route to use IP
error: pathspec 'route' did not match any file(s) known to git
error: pathspec 'to' did not match any file(s) known to git
error: pathspec 'use' did not match any file(s) known to git
error: pathspec 'IP'' did not match any file(s) known to git
Aborted.
Error: Command failed: git commit -m 'Update route to use IP'
    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at file:///XXXXXXXXXXXXXXXX/commitgpt/dist/index.js:122:25
    at step (file://XXXXXXXXXXXXXX/commitgpt/dist/index.js:33:23)
    at Object.next (file:///xxxxxxxxxxxxxxxxxxxx/commitgpt/dist/index.js:14:53)
    at fulfilled (file:///XXXXXXXXXXXXXXXXXXXX/commitgpt/dist/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12552,
  stdout: null,
  stderr: null
}

**Comment by martic** [comment]
Same as #7 Except 7 is on Powershell

**Comment by RomanHotsiy** [comment]
Dup of #7
